### ISSUE TITLE
README example returns errors

### ISSUE THREAD

**Issue by DoubleF3lix** [GrantGMiller/simple_tcp#1]
The client prints 
```
Client Connection Error: [WinError 10022] An invalid argument was supplie
Client Connection Error: timed out
The client is Disconnected
```
whenever it tries to send input, and the server doesn't log that's receiving any data

I copied the code directly from the README, as shown here:

Server:
```py
from simple_socket.tcp_server import SimpleTCPServer # try also SimpleSSLServer for semi-secure communication (it uses a self-signed cert)
server = SimpleTCPServer(3888)

server.onConnected = lambda client, state: print('Client {} is {}'.format(client, state))
server.onDisconnected = lambda client, state: print('Client {} is {}'.format(client, state))


def HandleRx(client, data):
    print('Server received {} from {}'.format(data, client))
    client.Send(b'Echo: ' + data + b'\r\n')

    if b'q' in data:
        # the server can force-close a connection
        # in this case,
        # the server will disconnect a client if they send the letter 'q'
        client.Disconnect()

print("running thing")

server.onReceive = HandleRx```

Client:
```py
import random
import time
from simple_socket.tcp_client import SimpleTCPClient # try also SimpleSSLClient for semi-secure communication (it does not verify the cert)

client = SimpleTCPClient('192.168.254.254', 1885)
print('client.Hostname=', client.Hostname)

# by default, the client will connect and attempt to maintain its connection.
# if you want to manually control the connection, pass autoConnect=False
# then use the .Connect() and .Disconnect() methods to manage your connection manually

client.onConnected = lambda _, state: print('The client is', state)
client.onDisconnected = lambda _, state: print('The client is', state)

client.onReceive = lambda _, data: print('Rx:', data)

while True:
    cmd = random.choice(['q', 'n', 'i'])
    print('sending:', cmd)
    if 'Connected' in client.ConnectionStatus:
        client.Send(cmd)
    time.sleep(5)```

**Comment by GrantGMiller** [comment]
The port numbers must match. You have 1885 and 3888. Pick one and use it on both the client and server. Also the I don’t know if you meant to use 192.168.254.254 when instantiating the client. That should be the IP address of the server. Your server may have a different IP address.

**Comment by DoubleF3lix** [comment]
Oh, thanks for the super quick response. It appears I'm blind.
I've fixed the port issue and exposed the port with ngrok, but it appears to make a new connection for each piece of data sent. Is this normal? Some output I got is below:
```
client.Hostname= 2.tcp.ngrok.io
The client is Connected
sending: i
The client is Disconnected
Rx: b''
sending: q
The client is Connected
The client is Disconnected
Rx: b''
sending: n
The client is Connected
sending: i
The client is Disconnected
Rx: b''
sending: n
The client is Connected
The client is Disconnected
Rx: b''
```

**Comment by GrantGMiller** [comment]
I suspect the server is disconnecting the socket.
When the server returns an empty bytestring (b'') that means the server forced the connection closed.
It could be an ngrok thing, not sure.
Can I see the server side code?

I ran this brief test from my PC(client) connecting to a device(server) on my local network to confirm:


    client = SimpleTCPClient('192.168.68.143', 23)
    client.onConnected = lambda _, state: print('SMD:', state)
    client.onDisconnected = lambda _, state: print('SMD:', state)

    def HandleRX(intf, data):
        print('HandleRX(', data)
        if 'Password:' in data.decode():
            intf.Send('extron\r')

    client.onReceive = HandleRX

    while 'Disconnected' in client.ConnectionStatus:
        print('waiting for connection')
        time.sleep(1)

    for i in range(3):
        time.sleep(1)
        msg = 'q'
        print('Send(', msg)
        client.Send(msg)

and this was the output


    
    SMD: Connected
    HandleRX( b'\r\n(c) Copyright 2020, Extron Electronics, SMD 202, V3.00, 60-1306-01\r\nFri, 18 Dec 2020 10:41:11\r\n\r\nPassword:'
    Send( q
    HandleRX( b'\r\nLogin Administrator\r\n'
    HandleRX( b'3.00\r\n'
    Send( q
    HandleRX( b'3.00\r\n'
    Send( q`

**Comment by DoubleF3lix** [comment]
I just used a modified version of the example in the readme
```py
from simple_socket.tcp_server import SimpleTCPServer # try also SimpleSSLServer for semi-secure communication (it uses a self-signed cert)
server = SimpleTCPServer(8000) # I use ngrok to expose this port

server.onConnected = lambda client, state: print('Client {} is {}'.format(client, state))
server.onDisconnected = lambda client, state: print('Client {} is {}'.format(client, state))


def HandleRx(client, data):
    print('Server received {} from {}'.format(data, client))
    client.Send(b'Echo: ' + data + b'\r\n')

    if b'q' in data:
        # the server can force-close a connection
        # in this case,
        # the server will disconnect a client if they send the letter 'q'
        client.Disconnect()


server.onReceive = HandleRx
```

The client code is 
```py
import random
import time
from simple_socket.tcp_client import SimpleTCPClient # try also SimpleSSLClient for semi-secure communication (it does not verify the cert)

client = SimpleTCPClient('ngrok_ip_here', ngrok_port_here)
print('client.Hostname=', client.Hostname)

# by default, the client will connect and attempt to maintain its connection.
# if you want to manually control the connection, pass autoConnect=False
# then use the .Connect() and .Disconnect() methods to manage your connection manually

client.onConnected = lambda _, state: print('The client is', state)
client.onDisconnected = lambda _, state: print('The client is', state)

client.onReceive = lambda _, data: print('Rx:', data)

while True:
    cmd = random.choice(['q', 'n', 'i'])
    print('sending:', cmd)
    if 'Connected' in client.ConnectionStatus:
        client.Send(cmd)
    time.sleep(5)
```

**Comment by GrantGMiller** [comment]
Yes that line that says "client.Disconnect()" causes the server and client to disconnect.
Then when the client tries to send again, it reconnects.

**Comment by DoubleF3lix** [comment]
Even removing the disconnect section shows that `HandleRx` isn't being called since the server terminal prints nothing and the client still prints this
```
client.Hostname= 2.tcp.ngrok.io
The client is Connected
sending: n
The client is Disconnected
Rx: b''
sending: n
The client is Connected
The client is Disconnected
Rx: b''
sending: i
The client is Connected
sending: q
The client is Disconnected
Rx: b''
sending: n
The client is Connected
The client is Disconnected
Rx: b''
sending: i
The client is Connected
sending: i
The client is Disconnected
Rx: b''
sending: n
The client is Connected
The client is Disconnected
Rx: b''
sending: n
```

Sorry for not elaborating

**Comment by GrantGMiller** [comment]
I was able to install ngrok and do some testing. I believe I have fixed the issue.
I just submitted a bug fix. 
You can install the new version and try it? https://pypi.org/project/simple-socket/0.0.7/

**Comment by DoubleF3lix** [comment]
I still get weird output.
```py
client.Hostname= 2.tcp.ngrok.io
The client is Connected
sending: q
The client is Disconnected
Rx: b''
sending: n
The client is Connected
The client is Disconnected
Rx: b''
sending: n
The client is Connected
sending: q
The client is Disconnected
Rx: b''
sending: n
```
Code is the same, and I also checked the version with `pip freeze` to confirm it is set to 0.0.7

However, I also recently discovered that I may not need to use TCP for my project and I could probably use HTTP, so I might do that instead. Sorry for the inconvenience.

**Comment by GrantGMiller** [comment]
I noticed that at one point I had to specify the listenAddress to work with ngrok. This may happen if you have more than one NIC on your PC enabled at the same time.
You can instantiate the server like this

    server = SimpleTCPServer(3888, listenAddress='localhost')

Or you can enter the IP Address of the NIC you want the server to run on, instead of localhost.
